config/routes.rb
Rails.application.routes.draw do
  get 'myfilters/index'

  post 'myfilters/:id/delete', to: "myfilters#delete", as: "myfilters_delete"

  get 'myfilters/add'
  get 'myfilters/update'

  get '/images/filter' , :to => "images#filter"

  get '/images/changeFormat/:image_id/:filter_id', to: 'images#changeFormat', as: "change_image_format"
  get '/images/reEdit/:image_id/:filter_id/:appliedFilters', to: 'images#reEdit', as: "image_reEdit"
  get '/images/save/:image_id/:appliedFilters', to: 'images#save', as: "image_save"
  get 'images/saveToDB'
  get 'images/trashbin'

  post 'images/:id/trash', to: "images#trash", as: "image_trash"

  post 'images/:id/restore', to: "images#restore", as: "image_restore"

  post 'images/share', to: "images#share", as: "image_share"

  get 'images/download/:id', to: "images#download", as: "image_download"

  get 'images/shareIndex'
  get '/images/view/:image_id', to: 'images#view', as: "image_view"

  get 'homepage/index'

  post 'images/cleartrash', to: "images#cleartrash", as: "images_cleartrash"

  root 'homepage#index'

  get 'help'    => 'homepage#help'
  get 'about'   => 'homepage#about'
  get 'contact' => 'homepage#contact'

  resources :images, only: [:index, :new, :create, :destroy, :edit]
  devise_for :users

end

app/models/myfilter.rb
class Myfilter < ActiveRecord::Base
	belongs_to :user
	belongs_to :filter
end

app/controllers/myfilters_controller.rb
require 'will_paginate/array'
class MyfiltersController < ApplicationController
  def index
  	@myfilter = Myfilter.where("user_id = ?", current_user.id)
  	@filters = []
	  @myfilter.each do |f| 
	   @filters << Filter.find(f.filter_id)
    end
  end

  def delete
  	myfilter = Myfilter.where("user_id = ?", current_user.id).where("filter_id=?", params[:id])
    myfilter.destroy(myfilter)
    redirect_to myfilters_index_path, notice:  "The Filter has been deleted."
  end

  def add
    @myfilter = Myfilter.where("user_id = ?", current_user.id)
    @ownfilters = []
    @myfilter.each do |f| 
      @ownfilters << Filter.find(f.filter_id)
       end
      @filters = Filter.all - @ownfilters
      @filters = @filters.paginate(page: params[:page], per_page: 8)
  end

  def update
    checkboxFilters = []
    for key in params.keys
        if key[0,6] == "filter"
          checkboxFilters.push(key[6, key.length+1])
        end
    end

    for checkboxFilter in checkboxFilters
        Myfilter.create(:user_id =>  current_user.id, :filter_id => checkboxFilter)
    end
    redirect_to myfilters_index_path, notice: "The Filters have been added."
  end
end

app/helpers/myfilters_helper.rb
module MyfiltersHelper
end

app/views/myfilters/add.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<%= form_tag("/myfilters/update" , :method => :get ) do %>
<div class = "addFilter">
<table class="table table-bordered table-striped tbstyle">
  <thead>
    <tr>
      <th style= "width:30px"></th>
      <th style= "width:70px;text-align:center;">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @filters.each do |filter|%>
      <tr>
      	 <% checkboxId = "filter" + filter.id.to_s %>
        <td style= "width:30px;text-align:center;"> <%= check_box_tag(checkboxId , "yes" , false ,  :class => "custom-checkbox") %></td>
        <td style= "width:70px;text-align:center;"><%= filter.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style= "margin-left:80px;">
<p style= "text_align:center">
<%= will_paginate @filters %>
</p>
</div>
<div style= "">
  <p style="text-align:center;">
  <%= submit_tag("Add", :class => "btn btn-primary addFIlterbt") %>
</p>
</div>
</div>
<% end %>

app/views/myfilters/delete.html.erb
<h1>Myfilters#delete</h1>
<p>Find me in app/views/myfilters/delete.html.erb</p>

app/views/myfilters/index.html.erb
<div class = "filterIndex">
<br />
<%= link_to "Add Filter", myfilters_add_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped tbstyle">
  <thead>
    <tr>
      <th style= "text-align:center">Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @filters.each do |filter|%>
      <tr>
        <td><%= filter.name %></td>
        
         <td>
          <%= button_to "Delete",  myfilters_delete_path(filter.id), method: :post, class: "btn btn-danger"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style= "margin-left:250px;">
<p style= "text_align:center">
</p>
</div>
</div>