config/routes.rb
Rails.application.routes.draw do
  get 'myfilters/index'

  post 'myfilters/:id/delete', to: "myfilters#delete", as: "myfilters_delete"

  get 'myfilters/add'
  get 'myfilters/update'

  get '/images/filter' , :to => "images#filter"

  get '/images/changeFormat/:image_id/:filter_id', to: 'images#changeFormat', as: "change_image_format"
  get '/images/reEdit/:image_id/:filter_id/:appliedFilters', to: 'images#reEdit', as: "image_reEdit"
  get '/images/save/:image_id/:appliedFilters', to: 'images#save', as: "image_save"
  get 'images/saveToDB'
  get 'images/trashbin'

  post 'images/:id/trash', to: "images#trash", as: "image_trash"

  post 'images/:id/restore', to: "images#restore", as: "image_restore"

  post 'images/share', to: "images#share", as: "image_share"

  get 'images/download/:id', to: "images#download", as: "image_download"

  get 'images/shareIndex'
  get '/images/view/:image_id', to: 'images#view', as: "image_view"

  get 'homepage/index'

  post 'images/cleartrash', to: "images#cleartrash", as: "images_cleartrash"

  root 'homepage#index'

  get 'help'    => 'homepage#help'
  get 'about'   => 'homepage#about'
  get 'contact' => 'homepage#contact'

  resources :images, only: [:index, :new, :create, :destroy, :edit]
  devise_for :users

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :user
	mount_uploader :url, UrlUploader # Tells rails to use this uploader for this model.
  	validates :name, presence: true # Make sure the owner's name is present.
	attr_accessor :istrash
	attr_accessor :ownerId
	attr_accessor :user_id
	# attr_accessor :id
end

app/controllers/images_controller.rb
require 'rubygems'
 require'rmagick'
 require 'Log.rb'
 require 'will_paginate/array'
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :destroy, :share, :index, :shareIndex, :edit, :changeFormat, :reEdit, :view, :cleartrash, :restore, :share, :trash, :trashbin, :download, :saveToDB, :save]

  def index
  	@images = Image.where("user_id = ?", current_user.id).where("istrash=?", "f")
    @images = @images.paginate(page: params[:page], per_page: 6)
  end

  def shareIndex
    
    @shareinfo = Shareinfo.where("useremail = ?", current_user.email)
    @images = []
    @shareinfo.each do |f| 
    begin
    my_record = Image.find(f.imageid)
    rescue ActiveRecord::RecordNotFound => e
    my_record = nil
    end
    if my_record
    @images <<my_record
  end
    end
  end

  def new
  	@image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user
    @image.isTrash = false
    if @image.save
      redirect_to images_path, notice: "The iamge #{@image.name} has been uploaded."
    else
      render "new"
    end
  end


  def edit
    @image = Image.find(params[:id])
    @myfilter = Myfilter.where("user_id = ?", current_user.id)
    @filters = []
    @myfilter.each do |f| 
    @filters << Filter.find(f.filter_id)
    end
    @lastVersion = Image.find_by("id = ?", @image.lastVersion)
    @nextVersions = Image.where("lastVersion = ?", @image.id)
    @nextVersions = @nextVersions.paginate(page: params[:page], per_page: 3)
    @filters = @filters.paginate(page: params[:page], per_page: 10)
  end

  def changeFormat
     @myfilter = Myfilter.where("user_id = ?", current_user.id)
     @filters = []
     @myfilter.each do |f| 
     @filters << Filter.find(f.filter_id)
     end
     @image = Image.find(params[:image_id])
     filter = Filter.find(params[:filter_id])
     img =  Magick::Image.read("public" + @image.url.to_s).first
     method = filter.value[0,filter.value.length-1]
     thumb = img.send(method)
     
     # If you want to save this image use following
     thumb.write("public/images/#{current_user.id}#{@image.id}.jpg")
     @newImage = "#{current_user.id}#{@image.id}"
     @appliedFilters = filter.name
     @lastVersion = Image.find_by("id = ?", @image.lastVersion)
     @nextVersions = Image.where("lastVersion = ?", @image.id)
     # otherwise send it to the browser as follows
     # send_data(thumb.to_blob, :disposition => 'inline', 
     #                        :type => 'image/jpg')  
      @nextVersions = @nextVersions.paginate(page: params[:page], per_page: 3)
      @filters = @filters.paginate(page: params[:page], per_page: 10)
  end

  def reEdit
     @myfilter = Myfilter.where("user_id = ?", current_user.id)
     @filters = []
     @myfilter.each do |f| 
     @filters << Filter.find(f.filter_id)
     end
     @image = Image.find(params[:image_id])
     filter = Filter.find(params[:filter_id])
     img =  Magick::Image.read("public/images/#{current_user.id}#{@image.id}.jpg").first
     method = filter.value[0,filter.value.length-1]
     thumb = img.send(method)
     
     # If you want to save this image use following
     thumb.write("public/images/#{current_user.id}#{@image.id}.jpg")
     @renewImage = "#{current_user.id}#{@image.id}"
     @appliedFilters = params[:appliedFilters]+","+filter.name
     @lastVersion = Image.find_by("id = ?", @image.lastVersion)
     @nextVersions = Image.where("lastVersion = ?", @image.id)
     # otherwise send it to the browser as follows
     # send_data(thumb.to_blob, :disposition => 'inline', 
     #                        :type => 'image/jpg')   
     @nextVersions = @nextVersions.paginate(page: params[:page], per_page: 3)
     @filters = @filters.paginate(page: params[:page], per_page: 10)
  end

  def save
    @image = Image.new
    @image.lastVersion = params[:image_id]
    @image.appliedFilters = params[:appliedFilters]
  end

  def saveToDB
     @image = Image.new
    @image.user = current_user
    @image.isTrash = false
    @image.lastVersion = params[:lastVersion]
    @image.appliedFilters = params[:appliedFilters]
    @image.name = params[:name]
    @image.tag = params[:tag]
    img =  Magick::Image.read("public/images/#{current_user.id}#{@image.lastVersion}.jpg").first
    lastImage = Image.find_by("id = ?", @image.lastVersion)
    lastUrl = lastImage.url.to_s

    for i in 1...lastUrl.length
      if lastUrl[-i] == "/"
          @url = lastUrl[0,(lastUrl.length-i+1)]
          break
        end
    end

    img.write("public#{@url}#{@image.name}.jpg")    
    image_url = "public#{@url}#{@image.name}.jpg"
    @image.url = File.open(File.join(Rails.root , image_url))
    if @image.save
      redirect_to edit_image_path(@image.id), notice: "The iamge #{@image.name} has been uploaded."
    else
      render "new"
    end
  end

  def download
    @image= Image.find(params[:id])
    send_file "public" + @image.url.to_s
  end

  def trashbin
    @images = Image.where("user_id = ?", current_user.id).where("isTrash = ?", "t")
  end

  def trash
    @image = Image.find(params[:id])
    @image.isTrash = true
    @image.save
    redirect_to images_path
  end

  def share
    @shareinfo = Shareinfo.new()
    @shareinfo.imageid = params[:id]
    @shareinfo.useremail = params[:email]

    begin
    my_record = User.find_by("email=?", @shareinfo.useremail)
    rescue ActiveRecord::RecordNotFound => e
    my_record = nil
    end
    if my_record
    @shareinfo.save
      redirect_to images_path, notice:  "The image has been shared to #{@shareinfo.useremail}."
    else
      redirect_to images_path, notice:  "Please enter the right email of the person you want to share with."
    end

    
  end

  def destroy
    Image.find(params[:id]).destroy
    redirect_to images_trashbin_path, notice:  "The image has been deleted."
  end

  def restore
    @image = Image.find(params[:id])
    @image.isTrash = false
    @image.save
    redirect_to images_trashbin_path, notice: "The image #{@image.name} has been sent back."
  end

  def cleartrash
    @images = Image.where("user_id = ?", current_user.id).where("isTrash = ?", "t")
    @images.each do |f|
      f.destroy
    end
    redirect_to images_trashbin_path, notice:  "Your trash bin has been cleared"
  end

  def view
     @image = Image.find_by("id = ?",params[:image_id])
  end

  


  private
  def image_params
    params.require(:image).permit(:name, :tag, :url, :ownerId, :isTrash, :appliedFilters, :lastVersion)
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/changeFormat.html.erb
<div class = "edit" >
    <div class = "left_panel">
    	<div class = "last_version" style= "width:100%">
        <h4 style ="margin-left:55px;", class = "head4">Last Version</h4>
          <div class = "tdiv">
        <table class="table table-condensed">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
      <tr>
        <% if @lastVersion %>
        <td><%=link_to image_tag(@lastVersion.url,size:"100")%></td>
        <td style= "width:100px"><%= link_to @lastVersion.name, edit_image_path(@lastVersion.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
    	</div>
    	<div class = "next_version">
        <p style="text-align:center;">
         <h4 style = "margin-top:30px;margin-left:55px", class = "head4">Next Version</h4>
       </p>
       <div class = "nexttdiv">
        <table class="table table-condensed" >
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
     <% if @nextVersions %>
   <% @nextVersions.each do |nextVersion|%>
      <tr>
        <td ><%=link_to image_tag(nextVersion.url,size:"100")%></td>
       <td><%= link_to nextVersion.name, edit_image_path(nextVersion.id) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
<p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
    	</div>
    </div>
      <div class = "main_content" >
        <div class = "image_info">
          <div class = "image_info2">
            <h4 class = "head4 htip">ImageName: <%=@image.name%></h4>
            <h4 class = "head4 htip">ImageTag: <%=@image.tag%></h4>
            <h4 class = "head4 htip">AppliedFilters: <%=@appliedFilters%></h4>
          </div>
        </div>
        <div class = "image">
             <%=link_to image_tag("#{@newImage}.jpg",size:"500")%>
        <div>
             <div class = "btDIv">
             <div class = "restoreDiv"> 
         <%= link_to "restore", edit_image_path(@image.id), :class => "btn btn-primary saveBt" %>     
      </div>
        </div class = "saveDiv"> 
         <%= link_to("save",{:controller =>'images',:action => 'save',:image_id =>@image.id,:appliedFilters =>@appliedFilters}, :class => "btn btn-primary saveBt")%>        
      </div>
    </div>
    </div>
      <div class = "right_panel">
        <h2 class = "head4">Filters</h2>
         <% @filters.each do |filter|%>
         <p style="text-align:center;">
          <%= link_to("#{filter.name}",{:controller =>'images',:action => 'reEdit',:image_id =>@image.id ,:filter_id =>filter.id ,:appliedFilters =>@appliedFilters}, :class => "btn btn-primary editBt")%> 
        </p>
          <% end %>
          <p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
      </div>
</div>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destory.html.erb
<h1>Images#destory</h1>
<p>Find me in app/views/images/destory.html.erb</p>

app/views/images/edit.html.erb
<div class = "edit" >
    <div class = "left_panel">
    	<div class = "last_version">
      
        <h4 style ="margin-left:55px;", class = "head4">Last Version</h4>
        <div class = "tdiv">
            <table class="table table-condensed">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
      <tr>
        <% if @lastVersion %>
        <td ><%=link_to image_tag(@lastVersion.url,size:"100")%></td>
        <td style= "width:100px"><%= link_to @lastVersion.name, edit_image_path(@lastVersion.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
    	</div>
    	<div class = "next_version">
       <p style="text-align:center;">
         <h4 style = "margin-top:30px;margin-left:55px", class = "head4">Next Version</h4>
       </p>
       <div class = "nexttdiv">
            <table class="table table-condensed">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
     <% if @nextVersions %>
    <% @nextVersions.each do |nextVersion|%>
      <tr>
        <td><%=link_to image_tag(nextVersion.url,size:"100")%></td>
        <td><%= link_to nextVersion.name, edit_image_path(nextVersion.id) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
<p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
    	</div>
    </div>
      <div class = "main_content" >
        <div class = "image_info" >
          <div class = "image_info2">
            <h4 class = "head4 htip">ImageName: <%=@image.name%></h4>
            <h4 class = "head4 htip">ImageTag: <%=@image.tag%></h4>
            <h4 class = "head4 htip">AppliedFilters: <%=@image.appliedFilters%></h4>
          </div>
        </div>
        <div class = "image">
          <%=link_to image_tag(@image.url,size:"500")%>
        </div>       
      </div>
      <div class = "right_panel">
         <h2 class = "head4">Filters</h2>
         <% @filters.each do |filter|%>
         <p style="text-align:center;">
          <%= link_to("#{filter.name}",{:controller =>'images',:action => 'changeFormat',:image_id =>@image.id ,:filter_id =>filter.id}, :class => "btn btn-primary editBt")%> 
        </p>
          <% end %>
          <p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
      </div>
</div>

app/views/images/index.html.erb
<%= link_to "New Image", new_image_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped" style = "text-align:center;">
  <thead>
    <tr style = "text-align:center;">
      <th style = "text-align:center;">Image</th>
      <th style = "text-align:center;">Name</th>
      <th style = "text-align:center;">Download Link</th>
      <th style = "text-align:center;">Share (Email)</th>
      <th style = "text-align:center;">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image|%>
      <tr>
        <td><%=link_to image_tag(image.url,size:"80"), edit_image_path(image.id)%></td>
        <td><%= link_to image.name, edit_image_path(image.id) %></td>
        <td><%= link_to "Download Image", image_download_path(image) %></td>
        <td>
          <form action="images/share" method="post">
            <p>
            <input class="form-control" style="width: 80%" type="text" name="email"> 
            <input type="submit" class="btn btn-primary submitBt"  value="Share">
          </p>
            <input type="hidden" name="id" value="<%=image.id%>" >
          </form>
        </td>
        <td>
          <%= button_to "Trash",  image_trash_path(image.id), method: :post, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class= "page">
<p style= "text_align:center">
<%= will_paginate @images%>
</p>
</div>

app/views/images/new.html.erb
<% if !@image.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @image,:class => "form-horizontal", html: { multipart: true } do |f|%>
   <%= f.label :name, :class => "col-sm-2 control-label"%>
    <%= f.text_field :name, :class => "form-control wellwidth", :placeholder => "Please input image name"%>
    <%= f.file_field :url %>
    <%= f.label :tag, :class => "col-sm-2 control-label"%>
    <%= f.text_field :tag, :class => "form-control wellwidth", :placeholder => "Please input image tag"%><br/>
    <p style="text-align:center;">
    <%= f.submit "Save", :class =>  "btn btn-primary wellbutton" %>
    </p>
  <% end %>
</div>

app/views/images/reEdit.html.erb
<div class = "edit" >
    <div class = "left_panel">
    	<div class = "last_version">
        <h4 style ="margin-left:55px;", class = "head4">Last Version</h4>
        <div class = "tdiv">
        <table class="table table-condensed">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
      <tr>
        <% if @lastVersion %>
        <td><%=link_to image_tag(@lastVersion.url,size:"100")%></td>
        <td style= "width:100px"><%= link_to @lastVersion.name, edit_image_path(@lastVersion.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
    	</div>
    	<div class = "next_version">
        <p style="text-align:center;">
         <h4 style = "margin-top:30px;margin-left:55px", class = "head4">Next Version</h4>
       </p>
       <div class = "nexttdiv">
        <table class="table table-condensed">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
     <% if @nextVersions %>
    <% @nextVersions.each do |nextVersion|%>
      <tr>
        <td><%=link_to image_tag(nextVersion.url,size:"100")%></td>
        <td><%= link_to nextVersion.name, edit_image_path(nextVersion.id) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
<p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
    	</div>
    </div>
      <div class = "main_content" >
        <div class = "image_info">
             <div class = "image_info2">
            <h4 class = "head4 htip">ImageName: <%=@image.name%></h4>
            <h4 class = "head4 htip">ImageTag: <%=@image.tag%></h4>
            <h4 class = "head4 htip">AppliedFilters: <%=@appliedFilters%></h4>
          </div>
        </div>
        <div class = "image">
             <%=link_to image_tag("#{@renewImage}.jpg",size:"500")%>
        <div>
             <div class = "btDIv">
             <div class = "restoreDiv"> 
         <%= link_to "restore", edit_image_path(@image.id), :class => "btn btn-primary saveBt" %>     
      </div>
        </div class = "saveDiv"> 
         <%= link_to("save",{:controller =>'images',:action => 'save',:image_id =>@image.id,:appliedFilters =>@appliedFilters}, :class => "btn btn-primary saveBt")%>        
      </div>
    </div>               
      </div>
      <div class = "right_panel">
        <h2 class = "head4">Filters</h2>
         <% @filters.each do |filter|%>
         <p style="text-align:center;">
          <%= link_to("#{filter.name}",{:controller =>'images',:action => 'reEdit',:image_id =>@image.id ,:filter_id =>filter.id ,:appliedFilters =>@appliedFilters}, :class => "btn btn-primary editBt")%> 
        </p>
          <% end %>
          <p style= "text_align:center">
<%= will_paginate @nextVersions, :page_links => false%>
</p>
      </div>
</div>

app/views/images/save.html.erb
<% if !@image.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_tag("/images/saveToDB", :method => :get) do %>
    <p>
   Name:<br />
   <%= text_field_tag "name", nil, :class => "form-control wellwidth", :placeholder => "Please input image name"%>
 </p>
    <p>
   Tag:<br />
   <%= text_field_tag"tag", nil, :class => "form-control wellwidth", :placeholder => "Please input image tag" %>
 </p>
    <%= text_field_tag("lastVersion" , @image.lastVersion , :style => "display:none")%>
    <%= text_field_tag("appliedFilters" , @image.appliedFilters, :style => "display:none")%>
    <p style= "text-align:center">
    <%= submit_tag 'Submit', class: "btn btn-primary"%>
    </p>
  <% end %>
</div>

app/views/images/shareIndex.html.erb
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th style= "text-align:center">Image</th>
      <th style= "text-align:center">Name</th>
      <th style= "text-align:center">Download Link</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image|%>
      <tr>
        <td style= "text-align:center"><%=link_to image_tag(image.url,size:"80"), image_view_path(image.id)%></td>
        <td style= "text-align:center"><%= link_to image.name, image_view_path(image.id) %></td>
        <td style= "text-align:center"><%= link_to "Download Image", image_download_path(image) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/images/trashbin.html.erb
<%= link_to "Clear Trash", images_cleartrash_path, method: :post, data: { confirm: "Do you really want to clear your trash bin?" }, class: "btn btn-primary" %>
<div style = "margin-top:10px;text-align: center;">
<table class="table table-bordered table-striped"style= "text-align: center">
  <thead>
    <tr>
      <th style= "text-align: center">Image</th>
      <th style= "text-align: center">Name</th>
      <th style= "text-align: center">Delete Time</th>
      <th style= "text-align: center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image|%>
      <tr>
        <td><%=link_to image_tag(image.url,size:"80")%></td>
        <td><%= image.name %></td>
        <td><%= image.updated_at %></td>
        <td><%= button_to "Restore",  image_restore_path(image), method: :post, class: "btn btn-primary"%><br /><%= button_to "Delete", image, method: :delete, data: { confirm: "Do you really want to delete this image?" }, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/images/view.html.erb
<div class = "main_content" style= "margin-left: 230px;" >
        <div class = "image_info" >
          <div class = "image_info2">
            <h4 class = "head4 htip">ImageName: <%=@image.name%></h4>
            <h4 class = "head4 htip">ImageTag: <%=@image.tag%></h4>
            <h4 class = "head4 htip">AppliedFilters: <%=@image.appliedFilters%></h4>
          </div>
        </div>
        <div class = "image">
          <%=link_to image_tag(@image.url,size:"500")%>
        </div>       
      </div>