config/routes.rb
Rails.application.routes.draw do
  get 'myfilters/index'

  post 'myfilters/:id/delete', to: "myfilters#delete", as: "myfilters_delete"

  get 'myfilters/add'
  get 'myfilters/update'

  get '/images/filter' , :to => "images#filter"

  get '/images/changeFormat/:image_id/:filter_id', to: 'images#changeFormat', as: "change_image_format"
  get '/images/reEdit/:image_id/:filter_id/:appliedFilters', to: 'images#reEdit', as: "image_reEdit"
  get '/images/save/:image_id/:appliedFilters', to: 'images#save', as: "image_save"
  get 'images/saveToDB'
  get 'images/trashbin'

  post 'images/:id/trash', to: "images#trash", as: "image_trash"

  post 'images/:id/restore', to: "images#restore", as: "image_restore"

  post 'images/share', to: "images#share", as: "image_share"

  get 'images/download/:id', to: "images#download", as: "image_download"

  get 'images/shareIndex'
  get '/images/view/:image_id', to: 'images#view', as: "image_view"

  get 'homepage/index'

  post 'images/cleartrash', to: "images#cleartrash", as: "images_cleartrash"

  root 'homepage#index'

  get 'help'    => 'homepage#help'
  get 'about'   => 'homepage#about'
  get 'contact' => 'homepage#contact'

  resources :images, only: [:index, :new, :create, :destroy, :edit]
  devise_for :users

end

app/views/layouts/_footer.html.erb
<div>
<footer class="footer">
	<div style= "margin-left:80px;">
  <small >
     The <a href="#">Majik</a>
     is your images butler</a>
  </small>
</div>
<div style= "margin-right: 100px;">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</div>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Majik", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
           <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Image <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My image", images_path %></li>
              <li><%= link_to "shared image", images_shareIndex_path %></li>
              <li><%= link_to "Trash", images_trashbin_path %></li>
            </ul>
          </li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Filter <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Filter", myfilters_index_path %></li>
              <li><%= link_to "Add Filter", myfilters_add_path %></li>
            </ul>
          </li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Upload <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Upload Image", new_image_path %></li>
            </ul>
          </li>
           <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
             
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
       </body>
</html>